### PR TITLE
-Level Zero Task- Rook(Elephant) and Pawn(Soldier)

### PR DESCRIPTION
**Pull request by ritvikm57**
Used Blender to model two chess pieces (Rook and Pawn) and design both black and white versions.

### CODE REVIEW

**Review by NubZoro — APPROVED** [review]
sorry for late reply but looks good :D

**Review by NubZoro — CHANGES_REQUESTED** [review]
follow the instructions and make a folder with ur username in level0 then upload files into that folder the project itself is good

**Comment by ritvikm57** [comment]
Changes have been made please check

**Comment by NubZoro** [comment]
sorry for the late reply but good work man

**Pull request merged**
